apiVersion: v1
kind: Service
metadata:
  name: vulntracker-api
  namespace: {{ include "vulntracker.namespace" . }}
  labels:
    {{- include "vulntracker.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vulntracker-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
