{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vulntracker-api-secrets
  namespace: {{ include "vulntracker.namespace" . }}
  labels:
    {{- include "vulntracker.api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: vulntracker-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.secretKey }}
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.adminApiKey }}
{{- end }}
